sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  include:
    - php: 5.5
      env: SILEX_VERSION='1.2.*'
    - php: 5.6
      env: SILEX_VERSION='1.3.*'
    - php: 7.0
      env: SILEX_VERSION='2.0.*'
    - php: 7.1
      env: SILEX_VERSION='2.0.*'
    - php: 7.1
      env: DEPS='dev'

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache


before_install:
  - composer self-update
  - if [ "$SILEX_VERSION" != "" ]; then composer require --no-update silex/silex=$SILEX_VERSION; fi;
  - if [ "$DEPS" = 'dev' ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - composer install --no-progress

before_script:
  - export PATH=./bin:$PATH

script:
  - phpspec run -f pretty --no-interaction
  - behat --strict -c tests/behat.yml.dist -p file
  - behat --strict -c tests/behat.yml.dist -p class